sonar.projectKey=sureshr17_azure-cicd
sonar.organization=sureshr17
sonar.projectName=Azure Deploy Manual
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,coverage/**
sonar.typescript.tsconfigPaths=tsconfig.app.json,tsconfig.spec.json

sonar.javascript.lcov.reportPaths=coverage/azure-deploymanual/lcov.info